//! Auto-generated instruction support code from isa.yaml
//! This file is generated by build.rs - do not edit manually

use crate::highlevel::instructions::InstructionFormat;

/// Complete mapping from opcode byte to mnemonic string
pub const OPCODE_TO_MNEMONIC: &[Option<&'static str>] = &[
    Some("ldundefined"),                  // 0x00
    Some("ldnull"),                       // 0x01
    Some("ldtrue"),                       // 0x02
    Some("ldfalse"),                      // 0x03
    Some("createemptyobject"),            // 0x04
    Some("createemptyarray"),             // 0x05
    Some("createarraywithbuffer"),        // 0x06
    Some("createobjectwithbuffer"),       // 0x07
    Some("newobjrange"),                  // 0x08
    Some("newlexenv"),                    // 0x09
    Some("add2"),                         // 0x0a
    Some("sub2"),                         // 0x0b
    Some("mul2"),                         // 0x0c
    Some("div2"),                         // 0x0d
    Some("mod2"),                         // 0x0e
    Some("eq"),                           // 0x0f
    Some("noteq"),                        // 0x10
    Some("less"),                         // 0x11
    Some("lesseq"),                       // 0x12
    Some("greater"),                      // 0x13
    Some("greatereq"),                    // 0x14
    Some("shl2"),                         // 0x15
    Some("shr2"),                         // 0x16
    Some("ashr2"),                        // 0x17
    Some("and2"),                         // 0x18
    Some("or2"),                          // 0x19
    Some("xor2"),                         // 0x1a
    Some("exp"),                          // 0x1b
    Some("typeof"),                       // 0x1c
    Some("tonumber"),                     // 0x1d
    Some("tonumeric"),                    // 0x1e
    Some("neg"),                          // 0x1f
    Some("not"),                          // 0x20
    Some("inc"),                          // 0x21
    Some("dec"),                          // 0x22
    Some("istrue"),                       // 0x23
    Some("isfalse"),                      // 0x24
    Some("isin"),                         // 0x25
    Some("instanceof"),                   // 0x26
    Some("strictnoteq"),                  // 0x27
    Some("stricteq"),                     // 0x28
    Some("callarg0"),                     // 0x29
    Some("callarg1"),                     // 0x2a
    Some("callargs2"),                    // 0x2b
    Some("callargs3"),                    // 0x2c
    Some("callthis0"),                    // 0x2d
    Some("callthis1"),                    // 0x2e
    Some("callthis2"),                    // 0x2f
    Some("callthis3"),                    // 0x30
    Some("callthisrange"),                // 0x31
    Some("supercallthisrange"),           // 0x32
    Some("definefunc"),                   // 0x33
    Some("definemethod"),                 // 0x34
    Some("defineclasswithbuffer"),        // 0x35
    Some("getnextpropname"),              // 0x36
    Some("ldobjbyvalue"),                 // 0x37
    Some("stobjbyvalue"),                 // 0x38
    Some("ldsuperbyvalue"),               // 0x39
    Some("ldobjbyindex"),                 // 0x3a
    Some("stobjbyindex"),                 // 0x3b
    Some("ldlexvar"),                     // 0x3c
    Some("stlexvar"),                     // 0x3d
    Some("lda.str"),                      // 0x3e
    Some("tryldglobalbyname"),            // 0x3f
    Some("trystglobalbyname"),            // 0x40
    Some("ldglobalvar"),                  // 0x41
    Some("ldobjbyname"),                  // 0x42
    Some("stobjbyname"),                  // 0x43
    Some("mov"),                          // 0x44
    None,                                 // 0x45 (gap in opcodes)
    Some("ldsuperbyname"),                // 0x46
    Some("stconsttoglobalrecord"),        // 0x47
    Some("sttoglobalrecord"),             // 0x48
    Some("ldthisbyname"),                 // 0x49
    Some("stthisbyname"),                 // 0x4a
    Some("ldthisbyvalue"),                // 0x4b
    Some("stthisbyvalue"),                // 0x4c
    Some("jmp"),                          // 0x4d
    Some("jmp"),                          // 0x4e (imm16 variant)
    Some("jeqz"),                         // 0x4f (imm8)
    Some("jeqz"),                         // 0x50 (imm16)
    Some("jnez"),                         // 0x51
    Some("jstricteqz"),                   // 0x52
    Some("jnstricteqz"),                  // 0x53
    Some("jeqnull"),                      // 0x54
    Some("jnenull"),                      // 0x55
    Some("jstricteqnull"),                // 0x56
    Some("jnstricteqnull"),               // 0x57
    Some("jequndefined"),                 // 0x58
    Some("jneundefined"),                 // 0x59
    Some("jstrictequndefined"),           // 0x5a
    Some("jnstrictequndefined"),          // 0x5b
    Some("jeq"),                          // 0x5c (register, imm8)
    Some("jne"),                          // 0x5d
    Some("jstricteq"),                    // 0x5e
    Some("jnstricteq"),                   // 0x5f
    Some("lda"),                          // 0x60
    Some("sta"),                          // 0x61
    Some("ldai"),                         // 0x62
    Some("fldai"),                        // 0x63
    Some("return"),                       // 0x64
    Some("returnundefined"),              // 0x65
    Some("getpropiterator"),              // 0x66
    Some("getiterator"),                  // 0x67
    Some("closeiterator"),                // 0x68
    Some("poplexenv"),                    // 0x69
    Some("ldnan"),                        // 0x6a
    Some("ldinfinity"),                   // 0x6b
    Some("getunmappedargs"),              // 0x6c
    Some("ldglobal"),                     // 0x6d
    Some("ldnewtarget"),                  // 0x6e
    Some("ldthis"),                       // 0x6f
    Some("ldhole"),                       // 0x70
    Some("createregexpwithliteral"),      // 0x71
    Some("createregexpwithliteralwide"),  // 0x72
    Some("callrange"),                    // 0x73
    Some("definefuncwide"),               // 0x74
    Some("defineclasswithbufferwide"),    // 0x75
    Some("gettemplaterobject"),           // 0x76
    Some("setobjectwithproto"),           // 0x77
    Some("stownbyvalue"),                 // 0x78
    Some("stownbyindex"),                 // 0x79
    Some("stownbyname"),                  // 0x7a
    Some("getmodulenamespace"),           // 0x7b
    Some("stmodulevar"),                  // 0x7c
    Some("ldlocalmodulevar"),             // 0x7d
    Some("ldexternalmodulevar"),          // 0x7e
    Some("stglobalvar"),                  // 0x7f
    Some("createemptyarraywide"),         // 0x80
    Some("createarraywithbufferwide"),    // 0x81
    Some("createobjectwithbufferwide"),   // 0x82
    Some("newobjrangewide"),              // 0x83
    Some("typeofwide"),                   // 0x84
    Some("ldobjbyvaluewide"),             // 0x85
    Some("stobjbyvaluewide"),             // 0x86
    Some("ldsuperbyvaluewide"),           // 0x87
    Some("ldobjbyindexwide"),             // 0x88
    Some("stobjbyindexwide"),             // 0x89
    Some("ldlexvarimm8"),                 // 0x8a
    Some("stlexvarimm8"),                 // 0x8b
    Some("tryldglobalbynamewide"),        // 0x8c
    Some("trystglobalbynamewide"),        // 0x8d
    Some("stownbynamewithnameset"),       // 0x8e
    Some("mov"),                          // 0x8f (v8 variant)
    Some("ldobjbynamewide"),              // 0x90
    Some("stobjbynamewide"),              // 0x91
    Some("ldsuperbynamewide"),            // 0x92
    Some("ldthisbynamewide"),             // 0x93
    Some("stthisbynamewide"),             // 0x94
    Some("ldthisbyvaluewide"),            // 0x95
    Some("stthisbyvaluewide"),            // 0x96
    Some("asyncgeneratorreject"),         // 0x97
    Some("jmp"),                          // 0x98 (imm32)
    Some("stownbyvaluewithnameset"),      // 0x99
    Some("jeqz"),                         // 0x9a (imm32)
    Some("jnez"),                         // 0x9b (imm16)
    Some("jnez"),                         // 0x9c (imm32)
    Some("jstricteqz"),                   // 0x9d (imm16)
    Some("jnstricteqz"),                  // 0x9e (imm16)
    Some("jeqnull"),                      // 0x9f (imm16)
    Some("jnenull"),                      // 0xa0 (imm16)
    Some("jstricteqnull"),                // 0xa1 (imm16)
    Some("jnstricteqnull"),               // 0xa2 (imm16)
    Some("jequndefined"),                 // 0xa3 (imm16)
    Some("jneundefined"),                 // 0xa4 (imm16)
    Some("jstrictequndefined"),           // 0xa5 (imm16)
    Some("jnstrictequndefined"),          // 0xa6 (imm16)
    Some("jeq"),                          // 0xa7 (register, imm16)
    Some("jne"),                          // 0xa8
    Some("jstricteq"),                    // 0xa9
    Some("jnstricteq"),                   // 0xaa
    Some("getiteratorwide"),              // 0xab
    Some("closeiteratorwide"),            // 0xac
    Some("ldsymbol"),                     // 0xad
    Some("asyncfunctionenter"),           // 0xae
    Some("ldfunction"),                   // 0xaf
    Some("debugger"),                     // 0xb0
    Some("creategeneratorobj"),           // 0xb1
    Some("createiterresultobj"),          // 0xb2
    Some("createobjectwithexcludedkeys"), // 0xb3
    Some("newobjapply"),                  // 0xb4
    Some("newobjapplywide"),              // 0xb5
    Some("newlexenvwithname"),            // 0xb6
    Some("createasyncgeneratorobj"),      // 0xb7
    Some("asyncgeneratorresolve"),        // 0xb8
    Some("supercallspread"),              // 0xb9
    Some("apply"),                        // 0xba
    Some("supercallarrowrange"),          // 0xbb
    Some("definegettersetterbyvalue"),    // 0xbc
    Some("dynamicimport"),                // 0xbd
    Some("definemethodwide"),             // 0xbe
    Some("resumegenerator"),              // 0xbf
    Some("getresumemode"),                // 0xc0
    Some("gettemplaterobjectwide"),       // 0xc1
    Some("delobjprop"),                   // 0xc2
    Some("suspendgenerator"),             // 0xc3
    Some("asyncfunctionawaituncaught"),   // 0xc4
    Some("copydataproperties"),           // 0xc5
    Some("starrayspread"),                // 0xc6
];

/// Complete mapping from opcode byte to instruction format
pub const OPCODE_TO_FORMAT: &[Option<InstructionFormat>] = &[
    Some(InstructionFormat::NONE),                    // 0x00 ldundefined
    Some(InstructionFormat::NONE),                    // 0x01 ldnull
    Some(InstructionFormat::NONE),                    // 0x02 ldtrue
    Some(InstructionFormat::NONE),                    // 0x03 ldfalse
    Some(InstructionFormat::NONE),                    // 0x04 createemptyobject
    Some(InstructionFormat::IMM8),                    // 0x05 createemptyarray
    Some(InstructionFormat::IMM8_ID16),               // 0x06 createarraywithbuffer
    Some(InstructionFormat::IMM8_ID16),               // 0x07 createobjectwithbuffer
    Some(InstructionFormat::IMM8_IMM8_V8),            // 0x08 newobjrange
    Some(InstructionFormat::IMM8),                    // 0x09 newlexenv
    Some(InstructionFormat::IMM8_V8),                 // 0x0a add2
    Some(InstructionFormat::IMM8_V8),                 // 0x0b sub2
    Some(InstructionFormat::IMM8_V8),                 // 0x0c mul2
    Some(InstructionFormat::IMM8_V8),                 // 0x0d div2
    Some(InstructionFormat::IMM8_V8),                 // 0x0e mod2
    Some(InstructionFormat::IMM8_V8),                 // 0x0f eq
    Some(InstructionFormat::IMM8_V8),                 // 0x10 noteq
    Some(InstructionFormat::IMM8_V8),                 // 0x11 less
    Some(InstructionFormat::IMM8_V8),                 // 0x12 lesseq
    Some(InstructionFormat::IMM8_V8),                 // 0x13 greater
    Some(InstructionFormat::IMM8_V8),                 // 0x14 greatereq
    Some(InstructionFormat::IMM8_V8),                 // 0x15 shl2
    Some(InstructionFormat::IMM8_V8),                 // 0x16 shr2
    Some(InstructionFormat::IMM8_V8),                 // 0x17 ashr2
    Some(InstructionFormat::IMM8_V8),                 // 0x18 and2
    Some(InstructionFormat::IMM8_V8),                 // 0x19 or2
    Some(InstructionFormat::IMM8_V8),                 // 0x1a xor2
    Some(InstructionFormat::IMM8_V8),                 // 0x1b exp
    Some(InstructionFormat::IMM8),                    // 0x1c typeof
    Some(InstructionFormat::IMM8),                    // 0x1d tonumber
    Some(InstructionFormat::IMM8),                    // 0x1e tonumeric
    Some(InstructionFormat::IMM8),                    // 0x1f neg
    Some(InstructionFormat::IMM8),                    // 0x20 not
    Some(InstructionFormat::IMM8),                    // 0x21 inc
    Some(InstructionFormat::IMM8),                    // 0x22 dec
    Some(InstructionFormat::NONE),                    // 0x23 istrue
    Some(InstructionFormat::NONE),                    // 0x24 isfalse
    Some(InstructionFormat::IMM8_V8),                 // 0x25 isin
    Some(InstructionFormat::IMM8_V8),                 // 0x26 instanceof
    Some(InstructionFormat::IMM8_V8),                 // 0x27 strictnoteq
    Some(InstructionFormat::IMM8_V8),                 // 0x28 stricteq
    Some(InstructionFormat::IMM8),                    // 0x29 callarg0
    Some(InstructionFormat::IMM8_V8),                 // 0x2a callarg1
    Some(InstructionFormat::IMM8_V8_V8),              // 0x2b callargs2
    Some(InstructionFormat::IMM8_V8_V8_V8),           // 0x2c callargs3
    Some(InstructionFormat::IMM8_V8),                 // 0x2d callthis0
    Some(InstructionFormat::IMM8_V8_V8),              // 0x2e callthis1
    Some(InstructionFormat::IMM8_V8_V8_V8),           // 0x2f callthis2
    Some(InstructionFormat::IMM8_V8_V8_V8_V8),        // 0x30 callthis3
    Some(InstructionFormat::IMM8_IMM8_V8),            // 0x31 callthisrange
    Some(InstructionFormat::IMM8_IMM8_V8),            // 0x32 supercallthisrange
    Some(InstructionFormat::IMM8_ID16_IMM8),          // 0x33 definefunc
    Some(InstructionFormat::IMM8_ID16_IMM8),          // 0x34 definemethod
    Some(InstructionFormat::IMM8_ID16_ID16_IMM16_V8), // 0x35 defineclasswithbuffer
    Some(InstructionFormat::V8),                      // 0x36 getnextpropname
    Some(InstructionFormat::IMM8_V8),                 // 0x37 ldobjbyvalue
    Some(InstructionFormat::IMM8_V8_V8),              // 0x38 stobjbyvalue
    Some(InstructionFormat::IMM8_V8),                 // 0x39 ldsuperbyvalue
    Some(InstructionFormat::IMM8_IMM16),              // 0x3a ldobjbyindex
    Some(InstructionFormat::IMM8_V8_IMM16),           // 0x3b stobjbyindex
    Some(InstructionFormat::IMM4_IMM4),               // 0x3c ldlexvar
    Some(InstructionFormat::IMM4_IMM4),               // 0x3d stlexvar
    Some(InstructionFormat::ID16),                    // 0x3e lda.str
    Some(InstructionFormat::IMM8_ID16),               // 0x3f tryldglobalbyname
    Some(InstructionFormat::IMM8_ID16),               // 0x40 trystglobalbyname
    Some(InstructionFormat::IMM16_ID16),              // 0x41 ldglobalvar
    Some(InstructionFormat::IMM8_ID16),               // 0x42 ldobjbyname
    Some(InstructionFormat::IMM8_ID16_V8),            // 0x43 stobjbyname
    Some(InstructionFormat::V4_V4),                   // 0x44 mov (v4)
    None,                                             // 0x45 (gap)
    Some(InstructionFormat::IMM8_ID16),               // 0x46 ldsuperbyname
    Some(InstructionFormat::IMM16_ID16),              // 0x47 stconsttoglobalrecord
    Some(InstructionFormat::IMM16_ID16),              // 0x48 sttoglobalrecord
    Some(InstructionFormat::IMM8_ID16),               // 0x49 ldthisbyname
    Some(InstructionFormat::IMM8_ID16_V8),            // 0x4a stthisbyname
    Some(InstructionFormat::IMM8_V8),                 // 0x4b ldthisbyvalue
    Some(InstructionFormat::IMM8_V8_V8),              // 0x4c stthisbyvalue
    Some(InstructionFormat::IMM32),                   // 0x4d jmp (imm32)
    Some(InstructionFormat::IMM16),                   // 0x4e jmp (imm16)
    Some(InstructionFormat::IMM8),                    // 0x4f jeqz (imm8)
    Some(InstructionFormat::IMM16),                   // 0x50 jeqz (imm16)
    Some(InstructionFormat::IMM8),                    // 0x51 jnez (imm8)
    Some(InstructionFormat::IMM8),                    // 0x52 jstricteqz (imm8)
    Some(InstructionFormat::IMM8),                    // 0x53 jnstricteqz (imm8)
    Some(InstructionFormat::IMM8),                    // 0x54 jeqnull (imm8)
    Some(InstructionFormat::IMM8),                    // 0x55 jnenull (imm8)
    Some(InstructionFormat::IMM8),                    // 0x56 jstricteqnull (imm8)
    Some(InstructionFormat::IMM8),                    // 0x57 jnstricteqnull (imm8)
    Some(InstructionFormat::IMM8),                    // 0x58 jequndefined (imm8)
    Some(InstructionFormat::IMM8),                    // 0x59 jneundefined (imm8)
    Some(InstructionFormat::IMM8),                    // 0x5a jstrictequndefined (imm8)
    Some(InstructionFormat::IMM8),                    // 0x5b jnstrictequndefined (imm8)
    Some(InstructionFormat::V8_IMM8),                 // 0x5c jeq (reg, imm8)
    Some(InstructionFormat::V8_IMM8),                 // 0x5d jne (reg, imm8)
    Some(InstructionFormat::V8_IMM8),                 // 0x5e jstricteq (reg, imm8)
    Some(InstructionFormat::V8_IMM8),                 // 0x5f jnstricteq (reg, imm8)
    Some(InstructionFormat::V8),                      // 0x60 lda
    Some(InstructionFormat::V8),                      // 0x61 sta
    Some(InstructionFormat::IMM32),                   // 0x62 ldai
    Some(InstructionFormat::IMM32),                   // 0x63 fldai
    Some(InstructionFormat::NONE),                    // 0x64 return
    Some(InstructionFormat::NONE),                    // 0x65 returnundefined
    Some(InstructionFormat::V8),                      // 0x66 getpropiterator
    Some(InstructionFormat::V8),                      // 0x67 getiterator
    Some(InstructionFormat::V8),                      // 0x68 closeiterator
    Some(InstructionFormat::NONE),                    // 0x69 poplexenv
    Some(InstructionFormat::NONE),                    // 0x6a ldnan
    Some(InstructionFormat::NONE),                    // 0x6b ldinfinity
    Some(InstructionFormat::NONE),                    // 0x6c getunmappedargs
    Some(InstructionFormat::NONE),                    // 0x6d ldglobal
    Some(InstructionFormat::NONE),                    // 0x6e ldnewtarget
    Some(InstructionFormat::NONE),                    // 0x6f ldthis
    Some(InstructionFormat::NONE),                    // 0x70 ldhole
    Some(InstructionFormat::IMM8_ID16),               // 0x71 createregexpwithliteral
    Some(InstructionFormat::IMM8_ID16_IMM16),         // 0x72 createregexpwithliteralwide
    Some(InstructionFormat::IMM8_IMM8_V8),            // 0x73 callrange
    Some(InstructionFormat::IMM16_ID16_IMM16),        // 0x74 definefuncwide
    Some(InstructionFormat::IMM16_ID16_IMM16_V8),     // 0x75 defineclasswithbufferwide
    Some(InstructionFormat::NONE),                    // 0x76 gettemplaterobject
    Some(InstructionFormat::IMM8_V8),                 // 0x77 setobjectwithproto
    Some(InstructionFormat::IMM8_V8_V8),              // 0x78 stownbyvalue
    Some(InstructionFormat::IMM8_V8_IMM16),           // 0x79 stownbyindex
    Some(InstructionFormat::IMM8_ID16_V8),            // 0x7a stownbyname
    Some(InstructionFormat::IMM8),                    // 0x7b getmodulenamespace
    Some(InstructionFormat::IMM8),                    // 0x7c stmodulevar
    Some(InstructionFormat::IMM8),                    // 0x7d ldlocalmodulevar
    Some(InstructionFormat::IMM8),                    // 0x7e ldexternalmodulevar
    Some(InstructionFormat::IMM8_V8),                 // 0x7f stglobalvar
    Some(InstructionFormat::IMM16),                   // 0x80 createemptyarraywide
    Some(InstructionFormat::IMM16_ID16_IMM16),        // 0x81 createarraywithbufferwide
    Some(InstructionFormat::IMM16_ID16_IMM16),        // 0x82 createobjectwithbufferwide
    Some(InstructionFormat::IMM16_IMM16_V8),          // 0x83 newobjrangewide
    Some(InstructionFormat::IMM16),                   // 0x84 typeofwide
    Some(InstructionFormat::IMM16_V8),                // 0x85 ldobjbyvaluewide
    Some(InstructionFormat::IMM16_V8_V8),             // 0x86 stobjbyvaluewide
    Some(InstructionFormat::IMM16_V8),                // 0x87 ldsuperbyvaluewide
    Some(InstructionFormat::IMM32),                   // 0x88 ldobjbyindexwide
    Some(InstructionFormat::IMM16_V8_IMM32),          // 0x89 stobjbyindexwide
    Some(InstructionFormat::IMM8_IMM8),               // 0x8a ldlexvarimm8
    Some(InstructionFormat::IMM8_IMM8),               // 0x8b stlexvarimm8
    Some(InstructionFormat::IMM16_ID16),              // 0x8c tryldglobalbynamewide
    Some(InstructionFormat::IMM16_ID16),              // 0x8d trystglobalbynamewide
    Some(InstructionFormat::IMM8_ID16_V8),            // 0x8e stownbynamewithnameset
    Some(InstructionFormat::V8_V8),                   // 0x8f mov (v8)
    Some(InstructionFormat::IMM16_ID16),              // 0x90 ldobjbynamewide
    Some(InstructionFormat::IMM16_ID16_V8),           // 0x91 stobjbynamewide
    Some(InstructionFormat::IMM16_ID16),              // 0x92 ldsuperbynamewide
    Some(InstructionFormat::IMM16_ID16),              // 0x93 ldthisbynamewide
    Some(InstructionFormat::IMM16_ID16_V8),           // 0x94 stthisbynamewide
    Some(InstructionFormat::IMM16_V8),                // 0x95 ldthisbyvaluewide
    Some(InstructionFormat::IMM16_V8_V8),             // 0x96 stthisbyvaluewide
    Some(InstructionFormat::NONE),                    // 0x97 asyncgeneratorreject
    Some(InstructionFormat::IMM32),                   // 0x98 jmp (imm32)
    Some(InstructionFormat::IMM8_V8_V8),              // 0x99 stownbyvaluewithnameset
    Some(InstructionFormat::IMM32),                   // 0x9a jeqz (imm32)
    Some(InstructionFormat::IMM16),                   // 0x9b jnez (imm16)
    Some(InstructionFormat::IMM32),                   // 0x9c jnez (imm32)
    Some(InstructionFormat::IMM16),                   // 0x9d jstricteqz (imm16)
    Some(InstructionFormat::IMM16),                   // 0x9e jnstricteqz (imm16)
    Some(InstructionFormat::IMM16),                   // 0x9f jeqnull (imm16)
    Some(InstructionFormat::IMM16),                   // 0xa0 jnenull (imm16)
    Some(InstructionFormat::IMM16),                   // 0xa1 jstricteqnull (imm16)
    Some(InstructionFormat::IMM16),                   // 0xa2 jnstricteqnull (imm16)
    Some(InstructionFormat::IMM16),                   // 0xa3 jequndefined (imm16)
    Some(InstructionFormat::IMM16),                   // 0xa4 jneundefined (imm16)
    Some(InstructionFormat::IMM16),                   // 0xa5 jstrictequndefined (imm16)
    Some(InstructionFormat::IMM16),                   // 0xa6 jnstrictequndefined (imm16)
    Some(InstructionFormat::V8_IMM16),                // 0xa7 jeq (reg, imm16)
    Some(InstructionFormat::V8_IMM16),                // 0xa8 jne (reg, imm16)
    Some(InstructionFormat::V8_IMM16),                // 0xa9 jstricteq (reg, imm16)
    Some(InstructionFormat::V8_IMM16),                // 0xaa jnstricteq (reg, imm16)
    Some(InstructionFormat::V8),                      // 0xab getiteratorwide
    Some(InstructionFormat::V8),                      // 0xac closeiteratorwide
    Some(InstructionFormat::NONE),                    // 0xad ldsymbol
    Some(InstructionFormat::NONE),                    // 0xae asyncfunctionenter
    Some(InstructionFormat::NONE),                    // 0xaf ldfunction
    Some(InstructionFormat::NONE),                    // 0xb0 debugger
    Some(InstructionFormat::V8),                      // 0xb1 creategeneratorobj
    Some(InstructionFormat::V8),                      // 0xb2 createiterresultobj
    Some(InstructionFormat::IMM8_V8_V8_V8),           // 0xb3 createobjectwithexcludedkeys
    Some(InstructionFormat::IMM8_V8_V8),              // 0xb4 newobjapply
    Some(InstructionFormat::IMM16_V8_V8),             // 0xb5 newobjapplywide
    Some(InstructionFormat::IMM8_ID16),               // 0xb6 newlexenvwithname
    Some(InstructionFormat::V8),                      // 0xb7 createasyncgeneratorobj
    Some(InstructionFormat::NONE),                    // 0xb8 asyncgeneratorresolve
    Some(InstructionFormat::V8),                      // 0xb9 supercallspread
    Some(InstructionFormat::IMM8_V8_V8),              // 0xba apply
    Some(InstructionFormat::IMM8_IMM8_V8),            // 0xbb supercallarrowrange
    Some(InstructionFormat::V8_V8_V8_V8),             // 0xbc definegettersetterbyvalue
    Some(InstructionFormat::NONE),                    // 0xbd dynamicimport
    Some(InstructionFormat::IMM16_ID16_IMM16),        // 0xbe definemethodwide
    Some(InstructionFormat::V8),                      // 0xbf resumegenerator
    Some(InstructionFormat::V8),                      // 0xc0 getresumemode
    Some(InstructionFormat::NONE),                    // 0xc1 gettemplaterobjectwide
    Some(InstructionFormat::V8_V8),                   // 0xc2 delobjprop
    Some(InstructionFormat::V8),                      // 0xc3 suspendgenerator
    Some(InstructionFormat::NONE),                    // 0xc4 asyncfunctionawaituncaught
    Some(InstructionFormat::V8_V8),                   // 0xc5 copydataproperties
    Some(InstructionFormat::V8_V8),                   // 0xc6 starrayspread
];

/// Reverse lookup: mnemonic string to opcode byte
pub const MNEMONIC_TO_OPCODE: &[(&'static str, u8)] = &[
    ("ldundefined", 0x00),
    ("ldnull", 0x01),
    ("ldtrue", 0x02),
    ("ldfalse", 0x03),
    ("createemptyobject", 0x04),
    ("createemptyarray", 0x05),
    ("createarraywithbuffer", 0x06),
    ("createobjectwithbuffer", 0x07),
    ("newobjrange", 0x08),
    ("newlexenv", 0x09),
    ("add2", 0x0a),
    ("sub2", 0x0b),
    ("mul2", 0x0c),
    ("div2", 0x0d),
    ("mod2", 0x0e),
    ("eq", 0x0f),
    ("noteq", 0x10),
    ("less", 0x11),
    ("lesseq", 0x12),
    ("greater", 0x13),
    ("greatereq", 0x14),
    ("shl2", 0x15),
    ("shr2", 0x16),
    ("ashr2", 0x17),
    ("and2", 0x18),
    ("or2", 0x19),
    ("xor2", 0x1a),
    ("exp", 0x1b),
    ("typeof", 0x1c),
    ("tonumber", 0x1d),
    ("tonumeric", 0x1e),
    ("neg", 0x1f),
    ("not", 0x20),
    ("inc", 0x21),
    ("dec", 0x22),
    ("istrue", 0x23),
    ("isfalse", 0x24),
    ("isin", 0x25),
    ("instanceof", 0x26),
    ("strictnoteq", 0x27),
    ("stricteq", 0x28),
    ("callarg0", 0x29),
    ("callarg1", 0x2a),
    ("callargs2", 0x2b),
    ("callargs3", 0x2c),
    ("callthis0", 0x2d),
    ("callthis1", 0x2e),
    ("callthis2", 0x2f),
    ("callthis3", 0x30),
    ("callthisrange", 0x31),
    ("supercallthisrange", 0x32),
    ("definefunc", 0x33),
    ("definemethod", 0x34),
    ("defineclasswithbuffer", 0x35),
    ("getnextpropname", 0x36),
    ("ldobjbyvalue", 0x37),
    ("stobjbyvalue", 0x38),
    ("ldsuperbyvalue", 0x39),
    ("ldobjbyindex", 0x3a),
    ("stobjbyindex", 0x3b),
    ("ldlexvar", 0x3c),
    ("stlexvar", 0x3d),
    ("lda.str", 0x3e),
    ("tryldglobalbyname", 0x3f),
    ("trystglobalbyname", 0x40),
    ("ldglobalvar", 0x41),
    ("ldobjbyname", 0x42),
    ("stobjbyname", 0x43),
    ("mov", 0x44),
    ("ldsuperbyname", 0x46),
    ("stconsttoglobalrecord", 0x47),
    ("sttoglobalrecord", 0x48),
    ("ldthisbyname", 0x49),
    ("stthisbyname", 0x4a),
    ("ldthisbyvalue", 0x4b),
    ("stthisbyvalue", 0x4c),
    ("jmp", 0x4d),                 // imm32 variant
    ("jmp", 0x4e),                 // imm16 variant
    ("jeqz", 0x4f),                // imm8
    ("jeqz", 0x50),                // imm16
    ("jnez", 0x51),                // imm8
    ("jstricteqz", 0x52),          // imm8
    ("jnstricteqz", 0x53),         // imm8
    ("jeqnull", 0x54),             // imm8
    ("jnenull", 0x55),             // imm8
    ("jstricteqnull", 0x56),       // imm8
    ("jnstricteqnull", 0x57),      // imm8
    ("jequndefined", 0x58),        // imm8
    ("jneundefined", 0x59),        // imm8
    ("jstrictequndefined", 0x5a),  // imm8
    ("jnstrictequndefined", 0x5b), // imm8
    ("jeq", 0x5c),                 // reg, imm8
    ("jne", 0x5d),                 // reg, imm8
    ("jstricteq", 0x5e),           // reg, imm8
    ("jnstricteq", 0x5f),          // reg, imm8
    ("lda", 0x60),
    ("sta", 0x61),
    ("ldai", 0x62),
    ("fldai", 0x63),
    ("return", 0x64),
    ("returnundefined", 0x65),
    ("getpropiterator", 0x66),
    ("getiterator", 0x67),
    ("closeiterator", 0x68),
    ("poplexenv", 0x69),
    ("ldnan", 0x6a),
    ("ldinfinity", 0x6b),
    ("getunmappedargs", 0x6c),
    ("ldglobal", 0x6d),
    ("ldnewtarget", 0x6e),
    ("ldthis", 0x6f),
    ("ldhole", 0x70),
    ("createregexpwithliteral", 0x71),
    ("createregexpwithliteralwide", 0x72),
    ("callrange", 0x73),
    ("definefuncwide", 0x74),
    ("defineclasswithbufferwide", 0x75),
    ("gettemplaterobject", 0x76),
    ("setobjectwithproto", 0x77),
    ("stownbyvalue", 0x78),
    ("stownbyindex", 0x79),
    ("stownbyname", 0x7a),
    ("getmodulenamespace", 0x7b),
    ("stmodulevar", 0x7c),
    ("ldlocalmodulevar", 0x7d),
    ("ldexternalmodulevar", 0x7e),
    ("stglobalvar", 0x7f),
    ("createemptyarraywide", 0x80),
    ("createarraywithbufferwide", 0x81),
    ("createobjectwithbufferwide", 0x82),
    ("newobjrangewide", 0x83),
    ("typeofwide", 0x84),
    ("ldobjbyvaluewide", 0x85),
    ("stobjbyvaluewide", 0x86),
    ("ldsuperbyvaluewide", 0x87),
    ("ldobjbyindexwide", 0x88),
    ("stobjbyindexwide", 0x89),
    ("ldlexvarimm8", 0x8a),
    ("stlexvarimm8", 0x8b),
    ("tryldglobalbynamewide", 0x8c),
    ("trystglobalbynamewide", 0x8d),
    ("stownbynamewithnameset", 0x8e),
    ("mov", 0x8f), // v8 variant
    ("ldobjbynamewide", 0x90),
    ("stobjbynamewide", 0x91),
    ("ldsuperbynamewide", 0x92),
    ("ldthisbynamewide", 0x93),
    ("stthisbynamewide", 0x94),
    ("ldthisbyvaluewide", 0x95),
    ("stthisbyvaluewide", 0x96),
    ("asyncgeneratorreject", 0x97),
    ("jmp", 0x98), // imm32
    ("stownbyvaluewithnameset", 0x99),
    ("jeqz", 0x9a),                // imm32
    ("jnez", 0x9b),                // imm16
    ("jnez", 0x9c),                // imm32
    ("jstricteqz", 0x9d),          // imm16
    ("jnstricteqz", 0x9e),         // imm16
    ("jeqnull", 0x9f),             // imm16
    ("jnenull", 0xa0),             // imm16
    ("jstricteqnull", 0xa1),       // imm16
    ("jnstricteqnull", 0xa2),      // imm16
    ("jequndefined", 0xa3),        // imm16
    ("jneundefined", 0xa4),        // imm16
    ("jstrictequndefined", 0xa5),  // imm16
    ("jnstrictequndefined", 0xa6), // imm16
    ("jeq", 0xa7),                 // reg, imm16
    ("jne", 0xa8),                 // reg, imm16
    ("jstricteq", 0xa9),           // reg, imm16
    ("jnstricteq", 0xaa),          // reg, imm16
    ("getiteratorwide", 0xab),
    ("closeiteratorwide", 0xac),
    ("ldsymbol", 0xad),
    ("asyncfunctionenter", 0xae),
    ("ldfunction", 0xaf),
    ("debugger", 0xb0),
    ("creategeneratorobj", 0xb1),
    ("createiterresultobj", 0xb2),
    ("createobjectwithexcludedkeys", 0xb3),
    ("newobjapply", 0xb4),
    ("newobjapplywide", 0xb5),
    ("newlexenvwithname", 0xb6),
    ("createasyncgeneratorobj", 0xb7),
    ("asyncgeneratorresolve", 0xb8),
    ("supercallspread", 0xb9),
    ("apply", 0xba),
    ("supercallarrowrange", 0xbb),
    ("definegettersetterbyvalue", 0xbc),
    ("dynamicimport", 0xbd),
    ("definemethodwide", 0xbe),
    ("resumegenerator", 0xbf),
    ("getresumemode", 0xc0),
    ("gettemplaterobjectwide", 0xc1),
    ("delobjprop", 0xc2),
    ("suspendgenerator", 0xc3),
    ("asyncfunctionawaituncaught", 0xc4),
    ("copydataproperties", 0xc5),
    ("starrayspread", 0xc6),
];
